### ISSUE TITLE
Repo is released on two crates on crates.io

### ISSUE THREAD

**Issue by tcharding** [BP-WG/bp-wallet#9]
Hi,

I noticed that this repository is released as [psbt](https://crates.io/crates/psbt) and also as [bp-wallet](https://crates.io/crates/bp-wallet), is there a reason for that?

I've been working on a new [rust-psbt](https://github.com/tcharding/rust-psbt) crate, it pulls the code out of `rust-bitcoin`, `rust-miniscript`, and then implements PSBTv2 on top of that.

Would you be willing to donate the `psbt` name on crates.io for this project?

Thanks for the consideration,
Tobin.

**Comment by dr-orlovsky** [comment]
This is not a crate, but repo, containing multiple crates - the same as rust-bitcoin. The reason is the same as there.

PSBT from this repo was the first crate implementing v1 and v2 PSBTs, and is independent from the rust-bitcoin ecosystem. There is no reason why I should transfer `pbst` crate name, which is used in many projects downstream, including RGB, projects by Bitfinex etc. You will have to use a different crate name.

**Comment by tcharding** [comment]
No worries, thanks.
